### ISSUE TITLE
Difficulty Getting Started From Neovim

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [lem-project/lem#587] opened 2022-09-17 18:54 UTC
Hello,

I have been eyeing `lem` for awhile and now that I am family making the jump to `nyxt` I decided I wanted to do the same with `lem`. The biggest issue I am having is that I like to heavily configure my text editors, but cannot find solid documentation on much. I am trying to start by porting my `neovim` configuration, or what of it applies, but aside from jumping through the source tree I cannot seem to make any real headway. Are there any plans to better documentation? I am having a hard time seeing what is even supported at the moment.

**Comment by cxxxr** [comment] 2022-09-18 01:13
Thank you for your feedback.

I think that frequently used symbols should be documented preferentially, but I don't write extensions so I don't know.
What use cases do you need?

**Comment by FOSSilizedDaemon** [comment] 2022-09-20 18:12
> Thank you for your feedback. I know I need documentation, but I haven't been able to get started.
> 
> I think that frequently used symbols should be documented preferentially, but I don't write extensions so I don't know. What use cases do you need?

I want to move to more common-lisp programs. Currently, I use `neovim`, but the only things keeping me there are UI related. I was considering moving to GNU Emacs, but it is too GUI oriented. I want to try `lem`, but the main issues I am having is figuring out what options are built into `lem` and what I need to port function wise.

**Comment by Sasanidas** [comment] 2023-06-03 20:42
Related to https://github.com/lem-project/lem/issues/644

Maybe now with the [webpage](https://lem-project.github.io/lem-page/) and the [keybindings](https://github.com/lem-project/lem/blob/main/docs/default-keybindings.md) is more easy to use.

Ping @FOSSilizedDaemon

**Comment by FOSSilizedDaemon** [comment] 2023-06-21 21:06
> 

Sorry for the late reply, work has me busy. I will look over those thank you.

**Comment by vindarel** [comment] 2023-06-22 11:43
Our startup files for inspiration:

- [@sasanidas](https://gitlab.com/sasanidas/lem-config/-/blob/master/init.lisp)
- [@vindarel](https://github.com/vindarel/lem-init)
- https://gist.github.com/jason-chandler/6332e3fd753fa87e3b1cd13582df5862 getting cxxxr/valtan to work along with paredit and the monokai theme

I also invite to test directly from Lem. It is discoverable: what functions are related to "line"? Type `(line` and tab-complete. Go to a symbol definition (M-.) and have a look at the other functions, etc.

**Comment by Sasanidas** [comment] 2023-12-07 15:17
My init files are now here https://codeberg.org/sasanidas/lem-config

I'll close this issue, as is not really an issue, but more of a question. Feel free to open it if the issue is not solved :+1:

**Closed by Sasanidas** 2023-12-07 15:17 UTC
