### ISSUE TITLE
In SDL2 version, resizing with yes/no dialog open kills lem

### ISSUE THREAD

**Issue by rsm-lisper** [lem-project/lem#1073] opened 2023-09-08 17:19 UTC
As in title, in SDL2 version when I resize window when yes/no dialog is open (to be exact - in Directory mode, when I try to delete something and get _"Really delete files ... [y/n]?"_ dialog) - lem crashes. In ncurses version it works fine.

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD tid=72660 "main thread" RUNNING {10040D0183}>:
  The assertion (LEM-CORE::VALID-WINDOW-HEIGHT-P LEM-CORE::HEIGHT) failed with
  LEM-CORE::HEIGHT = -1.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Retry assertion.
  1:            Return to the SDL2 main loop.
  2: [ABORT   ] Abort, quitting SDL2 entirely.

(SB-KERNEL:ASSERT-ERROR (LEM-CORE::VALID-WINDOW-HEIGHT-P LEM-CORE::HEIGHT) 1 LEM-CORE::HEIGHT -1)
0] 
```

**Comment by resttime** [comment] 2023-09-08 17:33
Confirmed reproducible and caused by #911 as well

**Comment by Sasanidas** [comment] 2023-12-07 14:22
Ping @rsm-lisper , seems like that one should be fixed https://github.com/lem-project/lem/issues/911, so I guess by extension this one also. I'll close the issue, feel free to re-open it if that's not then case :+1:

**Closed by Sasanidas** 2023-12-07 14:22 UTC
