### ISSUE TITLE
No right ctrl/alt on Windows 10

### ISSUE THREAD

**Issue by bryce-carson** [lem-project/lem#797] opened 2023-06-30 00:07 UTC
In the latest release binary for Windows (2.0.0) I am unable to do anything with the right alt and right control keys (C-g or M-x).

I don't usually use Windows, and I imagine this won't be a problem on Linux, but I thought I'd report it here.

```
Device name	DESKTOP-23AH0G3
Processor	AMD Ryzen 5 3400G with Radeon Vega Graphics       3.70 GHz
Installed RAM	8.00 GB (5.95 GB usable)
Device ID	************************************
Product ID	***********************
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Home
Version	22H2
Installed on	‎2020-‎08-‎17
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by VitoVan** [comment] 2023-06-30 08:16
I'm unable to run this 2.0.0 binary on Windows, either Windows 10 or Windows 11, no log, no nothing, the window just flashed and disappeared. I don't even know how to report my situation.

I just gave up on Windows binaries, at least for 2.0.0.

**Comment by bryce-carson** [comment] 2023-06-30 15:23
> no log, no nothing

Not even when launching the program using Powershell?

**Comment by VitoVan** [comment] 2023-06-30 23:02
> > no log, no nothing
> 
> Not even when launching the program using Powershell?

Yes, since you asked, I fired another issue for this with a screen cast: #804

**Comment by VitoVan** [comment] 2023-06-30 23:03
I can confirm your report that:

> I am unable to do anything with the right alt and right control keys (C-g or M-x).

even when running from source.

**Comment by preetpalS** [comment] 2023-07-26 11:03
Can confirm that right alt does nothing in the 2.1.0 binary release as well.

**Comment by cxxxr** [comment] 2023-10-23 13:40
https://github.com/lem-project/lem/commit/18f5e6a6f8b01dbf2d1d00e99f3cc90c8789d144#commitcomment-130093250
There have been stories like this in the past.

@vindarel 
I too think that perhaps treating alt_r as meta is the way to go, but there seems to be a problem with it not working satisfactorily in your environment.
Do you have a better solution?

**Comment by vindarel** [comment] 2023-10-24 10:55
Hi, it would be logical to merge the default that is right to most people. I don't have a better solution, at least we can change a parameter easily.

**Comment by elken** [comment] 2023-10-25 12:14
I don't understand lem's architecture well, a good way to settle it for both is some user setting that defaults to true for allowing `ALT_R` to be valid.

I can modify my PR to do this, if it supports user settings :smile:

**Comment by elken** [comment] 2024-01-12 13:11
@cxxxr what's your opinion here then? If you're happy for the above change I'll get around to making it when I can

**Comment by cxxxr** [comment] 2024-01-12 13:19
@elken 
https://github.com/lem-project/lem/pull/1143 This PR, right?
I'm okay with this change.

**Comment by elken** [comment] 2024-01-12 13:20
> @elken #1143 This PR, right? I'm okay with this change.

That's the one, okay I'll adjust it to be a user setting; then everyone wins :smile:

**Comment by cxxxr** [comment] 2024-01-12 13:29
@elken 
https://github.com/lem-project/lem/blob/98b81432f68aa53826fb02ef48754ccd2cd85419/frontends/sdl2/keyboard.lisp#L93
I think customization can be done by setting this variable.

**Comment by elken** [comment] 2024-01-12 13:33
So would you rather have that PR merged as-is?

**Comment by cxxxr** [comment] 2024-01-12 13:42
Yes, I think it is good.

**Comment by elken** [comment] 2024-01-12 13:59
Oh in that case then feel free :smile: I've unmarked it as a draft now

**Closed** 2024-01-12 14:21 UTC
